#!/bin/bash

current=$(brightnessctl g)
max=$(brightnessctl m)

percentage=$(( (current * 100) / max ))

if [ "$percentage" -lt 12 ]; then
    icon=""
elif [ "$percentage" -lt 25 ]; then
    icon=""
elif [ "$percentage" -lt 37 ]; then
    icon=""
elif [ "$percentage" -lt 50 ]; then
    icon=""
elif [ "$percentage" -lt 62 ]; then
    icon=""
elif [ "$percentage" -lt 75 ]; then
    icon=""
elif [ "$percentage" -lt 87 ]; then
    icon=""
elif [ "$percentage" -lt 100 ]; then
    icon=""
else
    icon=""
fi

bar_length=20
filled_length=$(( (bar_length * percentage) / 100 ))
empty_length=$(( bar_length - filled_length ))

for ((i=0; i<filled_length; i++)); do
    bar+="■"
done
for ((i=0; i<empty_length; i++)); do
    bar+="□"
done

dunstify -h string:x-dunst-stack-tag:brightness \
         -t 2000 \
         "$icon Brightness" \
         "$bar $percentage%"
