#!/bin/bash

WALLPAPER_DIR="$HOME/Downloads/wallpapers"

SELECTED_WALLPAPER=$(ls "$WALLPAPER_DIR" | wofi --dmenu)

if [ -z "$SELECTED_WALLPAPER" ]; then
    echo "No wallpaper selected."
    exit 1
fi

WALLPAPER="$WALLPAPER_DIR/$SELECTED_WALLPAPER"

swww img "$WALLPAPER"

echo "Wallpaper changed to $SELECTED_WALLPAPER"
