general.import = ["~/.config/alacritty/themes/themes/rose_pine.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
opacity = 1

[font]
normal.family = "Lilex Nerd Font"
bold.family = "Lilex Nerd Font"
italic.family = "Lilex Nerd Font"
size = 14

[colors.primary]
background = '#000000'

[[keyboard.bindings]]
key = "P"
mods = "Control|Shift"
command = { program = "/bin/zsh", args = ["-c","$HOME/.bin/alacritty-opacity.sh"] }
